
name: Pipeline CI

on:
  push:
    branches:
      - main
      - develop
      - feature/*
    
  pull_request:
    branches:
      - main
      - develop
      - feature/*

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      
      - name: Validate HTML Sintax (HTMLHint)
        run: |
          echo "Instalando o Validador de HTML"
          npm install -g htmlhint 
          echo "Executando análise"
          htmlhint index.html

      - name: Validate CSS Sintax (Stylelint)
        run: |
          echo "Instalando o validador de CSS"
          npm install -g stylelint stylelint-config-standard
          echo "Executando análise"
          npx stylelint style.css --config '{ "extends": ["stylelint-config-standard"] }'

      - name: Validate Code (Simulation)
        run: |
          echo "Simulando teste automatizado"