
name: Pipeline CI

on:
  push:
    branches:
      - main
      - develop
      - feature
    
  pull_request:
    branches:
      - main
      - develop
      - feature

jobs:
  lint and test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
      - use: actions/checkout@v3
      
      - name: Validar Sintaxe do HTML (HTMLHint)
      - run: |
          echo "Instalando o Validador de HTML"
          npm install -g htmlhint 
          echo "Executando análise"
          htmlhint indx.html

      - name: Validar Sintaxe do CSS (Stylelint)
        run: |
          echo "Instalando o validador de CSS"
          npm install -g stylelint stylelint-config-standard
          echo "Executando análise"
          npx stylelint style.css --config stylelint-config-standard

      - name: Validae Code (Simulação)
        run: |
          echo "Simulando teste automatizado"